cShareSystems.load_pas("ICARUS - <10 Players", [
    "coui://ui/mods/icarus/systems/monkey/execration_1v1 ns.pas",
    "coui://ui/mods/icarus/systems/anon/updated/regolith&steel_1v1_ns.pas",
    "coui://ui/mods/icarus/systems/anon/new/locket_2v2_ns.pas",
    "coui://ui/mods/icarus/systems/monkey/thoth_2v2 ns.pas",
    "coui://ui/mods/icarus/systems/anon/rolling_hills_2v2 ns.pas",
    "coui://ui/mods/icarus/systems/anon/beachfront_3v3 ns.pas",
    "coui://ui/mods/icarus/systems/monkey/hierophant_3v3 ns.pas",
    "coui://ui/mods/icarus/systems/anon/monstribus_3v3 ns.pas",
    "coui://ui/mods/icarus/systems/anon/new/porcupine_3v3_ns.pas",
    "coui://ui/mods/icarus/systems/anon/newnewnew/rafters_3v3 ns.pas",
    "coui://ui/mods/icarus/systems/monkey/scipio_4v4 ns.pas",
    "coui://ui/mods/icarus/systems/anon/updated/the_strip_4v4_ns.pas",
    "coui://ui/mods/icarus/systems/anon/new/stiring_4v4_ns.pas",
    "coui://ui/mods/icarus/systems/anon/new/telco_4v4_ns.pas",
    "coui://ui/mods/icarus/systems/anon/newnew/fission_4v4 ns.pas",
    "coui://ui/mods/icarus/systems/anon/newnew/fuse_4v4 ns.pas",
    "coui://ui/mods/icarus/systems/anon/newnewnew/appalachian_4v4 ns.pas",
    "coui://ui/mods/icarus/systems/anon/newnew/fussion_5v5 ns.pas",
    "coui://ui/mods/icarus/systems/monkey/fusile_5v5 ns.pas",
    "coui://ui/mods/icarus/systems/anon/the_iron_cross_5v5 ns.pas",
    "coui://ui/mods/icarus/systems/anon/middleearth_5v5 ns.pas",
    "coui://ui/mods/icarus/systems/anon/phantom_construct_5v5 ns.pas",
    "coui://ui/mods/icarus/systems/anon/ringoffire_5v5 ns.pas",
    "coui://ui/mods/icarus/systems/anon/sedimentary_5v5 ns.pas",
    "coui://ui/mods/icarus/systems/monkey/vulgar_masses_5v5 ns.pas",
    "coui://ui/mods/icarus/systems/monkey/war_infection_5v5 ns.pas",
    "coui://ui/mods/icarus/systems/anon/westward_5v5 ns.pas",
    "coui://ui/mods/icarus/systems/diss/john_is old_5v5 ns.pas",
    "coui://ui/mods/icarus/systems/anon/newnewnew/battle_of midway 5v5 ns.pas",
]);

cShareSystems.load_pas("ICARUS - 11+ Players", [
    "coui://ui/mods/icarus/systems/monkey/hell_wars_6v6 ns.pas",
    "coui://ui/mods/icarus/systems/anon/updated/xpres_6v6 ns.pas",
    "coui://ui/mods/icarus/systems/diss/the_ledge_6v6 ns.pas",
    "coui://ui/mods/icarus/systems/anon/new/icon_6v6_ns.pas",
    "coui://ui/mods/icarus/systems/diss/the_dried_lake_7v7 ns.pas",
    "coui://ui/mods/icarus/systems/diss/lava_chamber_7v7 ns.pas",
    "coui://ui/mods/icarus/systems/monkey/lion_killer_7v7 ns.pas",
    "coui://ui/mods/icarus/systems/anon/zpra_7v7 ns.pas",
    "coui://ui/mods/icarus/systems/monkey/colder_logic_8v8 ns.pas",
    "coui://ui/mods/icarus/systems/diss/the_blood_aqueduct_8v8 ns.pas",
    "coui://ui/mods/icarus/systems/monkey/fake_history_9v9 ns.pas",
    "coui://ui/mods/icarus/systems/monkey/killbox_10v10 ns.pas",
    "coui://ui/mods/icarus/systems/anon/tables_3v3v3v3 ns.pas",
    "coui://ui/mods/icarus/systems/anon/armadillo_3v3v3v3 ns.pas",
    "coui://ui/mods/icarus/systems/anon/newnewnew/squabble_4v4v4 ns.pas",
    "coui://ui/mods/icarus/systems/anon/newnewnew/bury_the ant 4v4v4v4 ns.pas",
    "coui://ui/mods/icarus/systems/anon/newnewnew/gateway_5v5v5 ns.pas",
    "coui://ui/mods/icarus/systems/anon/newnewnew/clockwork_5v5v5v5 ns.pas",
    "coui://ui/mods/icarus/systems/anon/newnew/glyptodon_6x3 ns.pas",
    "coui://ui/mods/icarus/systems/anon/ragnarok_6x3_6x2 ns.pas",
    "coui://ui/mods/icarus/systems/diss/juggernaut_6x2_4v4v4 ns.pas",
    "coui://ui/mods/icarus/systems/anon/new/gizmos_8v8v8_ns.pas",
    "coui://ui/mods/icarus/systems/anon/newnew/intrepid_16 ffa.pas",
    "coui://ui/mods/icarus/systems/anon/newnew/kuiper_18 ffa.pas",
    "coui://ui/mods/icarus/systems/anon/newnew/tirade_24 ffa.pas",
    "coui://ui/mods/icarus/systems/anon/newnew/guns_24 ffa.pas",
    "coui://ui/mods/icarus/systems/anon/newnew/kersmash_32 ffa.pas",
    "coui://ui/mods/icarus/systems/anon/newnew/the_maul 32 ffa.pas",
]);

cShareSystems.load_pas("ICARUS - Variable Size", [
    "coui://ui/mods/icarus/systems/diss/arid_lake hs 4v4-5v5.pas",
    "coui://ui/mods/icarus/systems/diss/burial_chambers hs 4v4-5v5.pas",
    "coui://ui/mods/icarus/systems/diss/beach_hs_4v4-6v6.pas",
    "coui://ui/mods/icarus/systems/diss/alcor_6v6_7v7 ds.pas",
    "coui://ui/mods/icarus/systems/anon/atree'splace ds.pas",
    "coui://ui/mods/icarus/systems/anon/dunes ds.pas",
    "coui://ui/mods/icarus/systems/anon/new/pebbles_ds.pas",
    "coui://ui/mods/icarus/systems/anon/tale_of_two_worlds ds.pas",
    "coui://ui/mods/icarus/systems/anon/updated/system-shock_ds.pas",
    "coui://ui/mods/icarus/systems/anon/updated/system-double_ds.pas",
    "coui://ui/mods/icarus/systems/anon/system-crash ds.pas",
    "coui://ui/mods/icarus/systems/anon/system_re-boot ds.pas",
    "coui://ui/mods/icarus/systems/anon/system-surge ds.pas",
    "coui://ui/mods/icarus/systems/anon/new/beasts_ds.pas",
    "coui://ui/mods/icarus/systems/diss/fools_journey_ds.pas",
    "coui://ui/mods/icarus/systems/anon/threepaths ds.pas",
    "coui://ui/mods/icarus/systems/anon/threepaths_x3 ds.pas",
    "coui://ui/mods/icarus/systems/anon/newnew/spark.pas",
    "coui://ui/mods/icarus/systems/anon/newnew/flash.pas",
    "coui://ui/mods/icarus/systems/anon/newnew/volt.pas",
    "coui://ui/mods/icarus/systems/anon/newnewnew/noiban_ffa.pas",
]);

cShareSystems.load_pas("ICARUS - Abnormal Spawns", [
    "coui://ui/mods/icarus/systems/anon/new/graveyardshift_3v3_ns.pas",
    "coui://ui/mods/icarus/systems/monkey/prison_colony_4v4 ns.pas",
    "coui://ui/mods/icarus/systems/monkey/dirge_field_6v6 ns.pas"
]);